// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#include "ui.h"

lv_obj_t *ui_Main = NULL;lv_obj_t *ui_HEART = NULL;lv_obj_t *ui_ACTIVITY = NULL;lv_obj_t *ui_STRESS = NULL;lv_obj_t *ui_BPM_LABEL = NULL;lv_obj_t *ui_BPM_VALUE = NULL;lv_obj_t *ui_ACTIVITY_LABEL = NULL;lv_obj_t *ui_ACTIVITY_VALUE = NULL;lv_obj_t *ui_STRESS_LABEL = NULL;lv_obj_t *ui_STRESS_VALUE = NULL;
// event funtions
void ui_event_HEART( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_BPM_VALUE, target, "", "");
}
}

void ui_event_ACTIVITY( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_ACTIVITY_VALUE, target, "", "");
}
}

void ui_event_STRESS( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_STRESS_VALUE, target, "", "");
}
}

// build funtions

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HEART = lv_arc_create(ui_Main);
lv_obj_set_width( ui_HEART, 220);
lv_obj_set_height( ui_HEART, 220);
lv_obj_set_align( ui_HEART, LV_ALIGN_CENTER );
lv_arc_set_range(ui_HEART, 0,200);
lv_arc_set_value(ui_HEART, 100);
lv_arc_set_bg_angles(ui_HEART,180,0);

lv_obj_set_style_arc_color(ui_HEART, lv_color_hex(0xFF4040), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HEART, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HEART, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HEART, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ACTIVITY = lv_arc_create(ui_Main);
lv_obj_set_width( ui_ACTIVITY, 220);
lv_obj_set_height( ui_ACTIVITY, 220);
lv_obj_set_align( ui_ACTIVITY, LV_ALIGN_CENTER );
lv_arc_set_value(ui_ACTIVITY, 50);
lv_arc_set_bg_angles(ui_ACTIVITY,95,170);

lv_obj_set_style_arc_color(ui_ACTIVITY, lv_color_hex(0x409AFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ACTIVITY, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ACTIVITY, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ACTIVITY, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_STRESS = lv_arc_create(ui_Main);
lv_obj_set_width( ui_STRESS, 220);
lv_obj_set_height( ui_STRESS, 220);
lv_obj_set_align( ui_STRESS, LV_ALIGN_CENTER );
lv_arc_set_value(ui_STRESS, 50);
lv_arc_set_bg_angles(ui_STRESS,10,85);
lv_arc_set_mode(ui_STRESS, LV_ARC_MODE_REVERSE);

lv_obj_set_style_arc_color(ui_STRESS, lv_color_hex(0xFFBC40), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_STRESS, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_STRESS, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_STRESS, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_BPM_LABEL = lv_label_create(ui_Main);
lv_obj_set_width( ui_BPM_LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BPM_LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BPM_LABEL, 0 );
lv_obj_set_y( ui_BPM_LABEL, -65 );
lv_obj_set_align( ui_BPM_LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_BPM_LABEL,"BPM");
lv_obj_set_style_text_color(ui_BPM_LABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BPM_LABEL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BPM_LABEL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BPM_VALUE = lv_label_create(ui_Main);
lv_obj_set_width( ui_BPM_VALUE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BPM_VALUE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BPM_VALUE, 0 );
lv_obj_set_y( ui_BPM_VALUE, -35 );
lv_obj_set_align( ui_BPM_VALUE, LV_ALIGN_CENTER );
lv_label_set_text(ui_BPM_VALUE,"100");
lv_obj_set_style_text_color(ui_BPM_VALUE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BPM_VALUE, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BPM_VALUE, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ACTIVITY_LABEL = lv_label_create(ui_Main);
lv_obj_set_width( ui_ACTIVITY_LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ACTIVITY_LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ACTIVITY_LABEL, -40 );
lv_obj_set_y( ui_ACTIVITY_LABEL, 10 );
lv_obj_set_align( ui_ACTIVITY_LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_ACTIVITY_LABEL,"Activity");
lv_obj_set_style_text_color(ui_ACTIVITY_LABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ACTIVITY_LABEL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ACTIVITY_LABEL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ACTIVITY_VALUE = lv_label_create(ui_Main);
lv_obj_set_width( ui_ACTIVITY_VALUE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ACTIVITY_VALUE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ACTIVITY_VALUE, -40 );
lv_obj_set_y( ui_ACTIVITY_VALUE, 40 );
lv_obj_set_align( ui_ACTIVITY_VALUE, LV_ALIGN_CENTER );
lv_label_set_text(ui_ACTIVITY_VALUE,"50");
lv_obj_set_style_text_color(ui_ACTIVITY_VALUE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ACTIVITY_VALUE, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ACTIVITY_VALUE, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_STRESS_LABEL = lv_label_create(ui_Main);
lv_obj_set_width( ui_STRESS_LABEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_STRESS_LABEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_STRESS_LABEL, 40 );
lv_obj_set_y( ui_STRESS_LABEL, 10 );
lv_obj_set_align( ui_STRESS_LABEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_STRESS_LABEL,"Stress");
lv_obj_set_style_text_color(ui_STRESS_LABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_STRESS_LABEL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_STRESS_LABEL, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_STRESS_VALUE = lv_label_create(ui_Main);
lv_obj_set_width( ui_STRESS_VALUE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_STRESS_VALUE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_STRESS_VALUE, 40 );
lv_obj_set_y( ui_STRESS_VALUE, 40 );
lv_obj_set_align( ui_STRESS_VALUE, LV_ALIGN_CENTER );
lv_label_set_text(ui_STRESS_VALUE,"50");
lv_obj_set_style_text_color(ui_STRESS_VALUE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_STRESS_VALUE, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_STRESS_VALUE, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HEART, ui_event_HEART, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ACTIVITY, ui_event_ACTIVITY, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_STRESS, ui_event_STRESS, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
   if (ui_Main) lv_obj_del(ui_Main);

// NULL screen variables
ui_Main= NULL;
ui_HEART= NULL;
ui_ACTIVITY= NULL;
ui_STRESS= NULL;
ui_BPM_LABEL= NULL;
ui_BPM_VALUE= NULL;
ui_ACTIVITY_LABEL= NULL;
ui_ACTIVITY_VALUE= NULL;
ui_STRESS_LABEL= NULL;
ui_STRESS_VALUE= NULL;

}
