// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t *ui_Main;
extern void ui_event_HEART( lv_event_t * e);
extern lv_obj_t *ui_HEART;
extern void ui_event_ACTIVITY( lv_event_t * e);
extern lv_obj_t *ui_ACTIVITY;
extern void ui_event_STRESS( lv_event_t * e);
extern lv_obj_t *ui_STRESS;
extern lv_obj_t *ui_BPM_LABEL;
extern lv_obj_t *ui_BPM_VALUE;
extern lv_obj_t *ui_ACTIVITY_LABEL;
extern lv_obj_t *ui_ACTIVITY_VALUE;
extern lv_obj_t *ui_STRESS_LABEL;
extern lv_obj_t *ui_STRESS_VALUE;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

