// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#include "ui.h"

lv_obj_t *ui_Pairing = NULL;lv_obj_t *ui_Title = NULL;lv_obj_t *ui_Code = NULL;lv_obj_t *ui_Subtitle = NULL;
// event funtions

// build funtions

void ui_Pairing_screen_init(void)
{
ui_Pairing = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Pairing, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Title = lv_label_create(ui_Pairing);
lv_obj_set_width( ui_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Title, 0 );
lv_obj_set_y( ui_Title, -35 );
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title,"Pairing Device");
lv_obj_set_style_text_color(ui_Title, lv_color_hex(0x37E23F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Code = lv_label_create(ui_Pairing);
lv_obj_set_width( ui_Code, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Code, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Code, LV_ALIGN_CENTER );
lv_label_set_text(ui_Code,"------");
lv_obj_set_style_text_font(ui_Code, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Subtitle = lv_label_create(ui_Pairing);
lv_obj_set_width( ui_Subtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Subtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Subtitle, 0 );
lv_obj_set_y( ui_Subtitle, 35 );
lv_obj_set_align( ui_Subtitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_Subtitle,"Enter code to web app");
lv_obj_set_style_text_font(ui_Subtitle, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Pairing_screen_destroy(void)
{
   if (ui_Pairing) lv_obj_del(ui_Pairing);

// NULL screen variables
ui_Pairing= NULL;
ui_Title= NULL;
ui_Code= NULL;
ui_Subtitle= NULL;

}
