// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#ifndef UI_PAIRING_H
#define UI_PAIRING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Pairing
extern void ui_Pairing_screen_init(void);
extern void ui_Pairing_screen_destroy(void);
extern lv_obj_t *ui_Pairing;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_Code;
extern lv_obj_t *ui_Subtitle;
extern lv_obj_t *ui_Spinner3;
extern lv_obj_t *ui_Image11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

