// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Splash
extern void ui_Splash_screen_init(void);
extern void ui_Splash_screen_destroy(void);
extern lv_obj_t *ui_Splash;
extern lv_obj_t *ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

