// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFi
extern void ui_WiFi_screen_init(void);
extern void ui_WiFi_screen_destroy(void);
extern lv_obj_t *ui_WiFi;
extern lv_obj_t *ui_Wifi_Title;
extern lv_obj_t *ui_IP_Address;
extern lv_obj_t *ui_WiFI_Subtitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

