// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Capstone_Display

#include "ui.h"

lv_obj_t *ui_WiFi = NULL;lv_obj_t *ui_Wifi_Title = NULL;lv_obj_t *ui_IP_Address = NULL;lv_obj_t *ui_WiFI_Subtitle = NULL;
// event funtions

// build funtions

void ui_WiFi_screen_init(void)
{
ui_WiFi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Wifi_Title = lv_label_create(ui_WiFi);
lv_obj_set_width( ui_Wifi_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Wifi_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Wifi_Title, 0 );
lv_obj_set_y( ui_Wifi_Title, -40 );
lv_obj_set_align( ui_Wifi_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Wifi_Title,"WiFi Setup");
lv_obj_set_style_text_color(ui_Wifi_Title, lv_color_hex(0x03D5FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Wifi_Title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Wifi_Title, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IP_Address = lv_label_create(ui_WiFi);
lv_obj_set_width( ui_IP_Address, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_IP_Address, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_IP_Address, LV_ALIGN_CENTER );
lv_label_set_text(ui_IP_Address,"192.168.4.1");
lv_obj_set_style_text_font(ui_IP_Address, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WiFI_Subtitle = lv_label_create(ui_WiFi);
lv_obj_set_width( ui_WiFI_Subtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WiFI_Subtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WiFI_Subtitle, 0 );
lv_obj_set_y( ui_WiFI_Subtitle, 40 );
lv_obj_set_align( ui_WiFI_Subtitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_WiFI_Subtitle,"Enter IP to any browser");

}

void ui_WiFi_screen_destroy(void)
{
   if (ui_WiFi) lv_obj_del(ui_WiFi);

// NULL screen variables
ui_WiFi= NULL;
ui_Wifi_Title= NULL;
ui_IP_Address= NULL;
ui_WiFI_Subtitle= NULL;

}
